<a href="https://colab.research.google.com/github/yabaroah/everpeak-analysis/blob/main/SPRINT_7_TT_DA_97_Let's_get_better.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 📤 __IMPORTS PRINCIPALES Y CONFIGURACIONES GLOBALES__⚙️
---

In [ ]:
#IMPORTS PRINCIPALES:
import pandas  as pd               #LECTURA, MANEJO Y TRANSFORMACIÓN DE DATAFRAMES.
import numpy   as np               #FUNCIONES MATEMÁTICAS RELEVANTES.
import matplotlib.pyplot as plt    #GRÁFICOS.
import seaborn as sns              #GRÁFICOS PRETTY.

#CONFIGURACIONES GLOBALES: EJEMPLOS.
import warnings                                                #MANEJO DE WARNINGS - ADVERTENCIAS
warnings.simplefilter(action='ignore', category=FutureWarning) #QUITAR WARNINGS MOLESTOS
pd.set_option('display.max_columns', None)                     #ELIMINA LIMITES DE PANDAS PARA MOSTRAR COLUMNAS
pd.set_option('display.max_rows', None)                        #ELIMINA LIMITES DE PANDAS PARA MOSTRAR FILAS
pd.set_option('display.max_colwidth', None)                    #AUTOAJUSTA ANCHO DE COLUMNAS

## 🗂️__LEYENDO DATA  + GENERAR PANDAS DATAFRAME__📊
---

In [ ]:
#CARGANDO DATA: ESTE DATASET SE ECUENTRA ALMACENADO EN REPOSITORIO DE GITHUB.
ruta_tabla = "https://media.githubusercontent.com/media/hector1994/e_commerce_funnel_data_generator/refs/heads/master/sales_data_dirty_sp7_data.csv"

df_raw     = pd.read_csv(ruta_tabla)  #DATA SIN PROCESAR.
df_raw.tail(3)                        #MUESTRAS LOS PRIMEROS 5 REGISTROS DEL DATAFRAME - df.tail()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
2000997,391cd401-d836-41b6-b3d0-a8066f57a408,2025-11-28,227119,Raquel García,raquel.garcía_227119@example.com,México,MEX,Tijuana,281 Calle Oeste,P003,Wireless Mouse,Accessories,1,25.5,0.1,5.15,25.5,2.55,4.3605,32.4605,PayPal,Delivered
2000998,eea17a44-2d6d-4d8f-a111-e1fd5c07cc79,2025-05-04,399283,Carlos Vargas,carlos.vargas_399283@example.com,Brasil,BRA,São Paulo,3065 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,3,250.0,0.9,6.35,750.0,0.00,142.5000,898.8500,Credit Card,Shipped
2000999,329e37d4-6d56-49a6-881e-6a1b8e4ad54a,2025-02-27,92854,Josefa Díaz,josefa.díaz_92854@example.com,Brasil,BRA,Brasília,3770 Calle Oeste,P015,Hair Dryer,Home,2,35.0,1.2,6.80,70.0,0.00,13.3000,90.1000,Debit Card,Delivered

## 🗺️__COMENCEMOS A EXPLORAR__📚
---

In [ ]:
#HACEMOS UNA COPIA PROFUNDA.
df_work = df_raw.copy(deep = True)

In [ ]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.6,5.90,35.0,0.0,6.650,47.550,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.0,0.2,5.30,800.0,40.0,144.400,909.700,Bank Transfer,Delivered

## 🧹 __LIMPIEMOS Y ESTANDARICEMOS UN "POCO" 🫧🧺__
---

In [ ]:
#REVISEMOS LAS COLUMNAS CATEGÓRICAS BUSCANDO ESTANDARIZAR.
df_work.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_name',
       'customer_email', 'customer_country', 'country_code', 'customer_city',
       'customer_address', 'product_id', 'product_name', 'product_category',
       'quantity', 'price_per_unit', 'total_weight', 'shipping_cost',
       'total_amount_gross', 'discount_amount', 'tax_amount',
       'final_total_amount', 'payment_method', 'shipping_status'],
      dtype='object')

In [ ]:
#REVISAMOS customer_country
df_work['customer_country'].unique()

array(['Chile', 'Colombia', 'Argentina', 'Perú', 'Brasil', 'México',
       'Ecuador', 'Uruguay'], dtype=object)

In [ ]:
df_work['customer_country'].nunique()

8

In [ ]:
df_work['customer_country'].value_counts(normalize = True)*100

customer_country
Brasil       40.166317
México       24.900650
Colombia      9.972214
Argentina     8.897451
Perú          7.027986
Chile         3.978061
Ecuador       3.033633
Uruguay       2.023688
Name: proportion, dtype: float64

In [ ]:
#PRODUCT CATEGORY
df_work['product_category'].unique()

array(['Electronics', 'Home', 'Furniture', 'Accessories', 'Fashion'],
      dtype=object)

In [ ]:
100*df_work['product_category'].value_counts(normalize = True)

product_category
Electronics    29.377961
Home           23.244528
Fashion        22.598201
Furniture      12.948576
Accessories    11.830735
Name: proportion, dtype: float64

In [ ]:
df_work.describe() #ENTREGA UN ANÁLISIS ESTADÍSTICO BÁSICO DE LAS COLUMNAS NUMÉRICAS.

,customer_id,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount
count,2.001000e+06,2.001000e+06,1.996998e+06,1.999000e+06,1.990998e+06,2.001000e+06,2.001000e+06,1.980994e+06,2.001000e+06
mean,2.009891e+05,1.566664e+00,2.711057e+02,8.656637e+00,1.798543e+01,4.259039e+02,1.488349e+01,7.809408e+01,5.058407e+02
std,1.155219e+05,1.211852e+00,3.187076e+02,2.006528e+01,3.010129e+01,7.119443e+02,5.039046e+01,1.308476e+02,8.311390e+02
min,1.000000e+03,-1.000000e+01,2.000000e+01,1.000000e-01,5.150000e+00,2.000000e+01,0.000000e+00,3.040000e+00,1.217000e+01
25%,1.007828e+05,1.000000e+00,4.500000e+01,6.000000e-01,5.900000e+00,7.000000e+01,0.000000e+00,1.292000e+01,8.697000e+01
50%,2.009380e+05,1.000000e+00,1.200000e+02,2.200000e+00,8.300000e+00,1.500000e+02,0.000000e+00,2.850000e+01,1.985000e+02
75%,3.011430e+05,2.000000e+00,3.000000e+02,1.000000e+01,2.000000e+01,5.000000e+02,8.500000e+00,9.500000e+01,6.052500e+02
max,4.009990e+05,1.000000e+01,1.200000e+03,4.500000e+02,6.800000e+02,1.200000e+04,2.400000e+03,2.280000e+03,1.432250e+04

In [ ]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001000 entries, 0 to 2000999
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   order_id            object
 1   order_date          object
 2   customer_id         int64
 3   customer_name       object
 4   customer_email      object
 5   customer_country    object
 6   country_code        object
 7   customer_city       object
 8   customer_address    object
 9   product_id          object
 10  product_name        object
 11  product_category    object
 12  quantity            int64
 13  price_per_unit      float64
 14  total_weight        float64
 15  shipping_cost       float64
 16  total_amount_gross  float64
 17  discount_amount     float64
 18  tax_amount          float64
 19  final_total_amount  float64
 20  payment_method      object
 21  shipping_status     object
dtypes: float64(7), int64(2), object(13)
memory usage: 335.9+ MB

In [ ]:
#FILTROS
df_work[(df_work['customer_country'] == 'Chile') & (df_work['customer_city'] == 'Rancagua')].head(10)

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.5,302.95,PayPal,Delivered
112,c28a9c3a-fe72-499f-ac69-8069ab57971e,2024-03-19,38852,Jorge Rojas,jorge.rojas_38852@example.com,Chile,CHL,Rancagua,4960 Calle Norte,P002,Smartphone X,Electronics,2,800.0,0.4,5.60,1600.0,0.0,304.0,1909.60,Credit Card,Shipped
262,14d6db8c-aaf8-41b6-bfb7-9521dc2feb8f,2024-08-14,225794,Sofía Acosta,sofía.acosta_225794@example.com,Chile,CHL,Rancagua,242 Calle Los Alamos,P009,Running Shoes,Fashion,2,120.0,1.6,7.40,240.0,0.0,45.6,293.00,PayPal,Shipped
469,d5d4e80c-1d2e-473c-b92f-921cb9f54781,2025-11-25,369222,Mateo López,mateo.lópez_369222@example.com,Chile,CHL,Rancagua,7432 Calle Oeste,P014,Microwave Oven,Home,3,150.0,30.0,50.00,450.0,90.0,68.4,478.40,PayPal,Processing
701,5c586108-e36e-419d-8f0d-c1dbe1864b99,2025-06-21,308514,Paula Martínez,paula.martínez_308514@example.com,Chile,CHL,Rancagua,6888 Calle Este,P002,Smartphone X,Electronics,2,800.0,0.4,5.60,1600.0,0.0,304.0,1909.60,Credit Card,Delivered
748,6077fec7-85ef-4d1f-8273-9ad779c46ea7,2025-06-10,382160,Jorge Gomez,jorge.gomez_382160@example.com,Chile,CHL,Rancagua,3704 Calle Norte,P012,Headphones NoiseCancelling,Electronics,3,250.0,NaN,6.35,750.0,0.0,142.5,898.85,Bank Transfer,Shipped
798,fb60bc29-ab93-449d-b50f-c633fea9588b,2024-04-22,26557,María Vargas,maría.vargas_26557@example.com,Chile,CHL,Rancagua,5029 Calle Los Alamos,P005,Monitor 27in,Electronics,1,300.0,5.0,12.50,300.0,30.0,51.3,333.80,Credit Card,Cancelled
989,65d52228-0e16-486b-921c-beb2ec2c5c80,2025-10-12,16787,María Silva,maría.silva_16787@example.com,Chile,CHL,Rancagua,9486 Calle Los Alamos,P005,Monitor 27in,Electronics,1,300.0,5.0,12.50,300.0,0.0,57.0,369.50,Debit Card,Shipped
1198,26e14405-33e4-409e-9ac1-b68af2c95fad,2024-09-18,210764,Felipe Díaz,felipe.díaz_210764@example.com,Chile,CHL,Rancagua,8535 Calle Principal,P001,Laptop Pro,Electronics,1,1200.0,2.5,8.75,1200.0,0.0,228.0,1436.75,Credit Card,Processing
1794,17720203-cf90-4f1c-9bc8-b909e32323cf,2024-11-05,240272,Ana Muñoz,ana.muñoz_240272@example.com,Chile,CHL,Rancagua,7894 Calle Los Alamos,P011,Smart TV 55in,Electronics,1,600.0,12.0,23.00,600.0,0.0,114.0,737.00,Credit Card,Shipped

In [ ]:
#MANEJO DE VALORES NULOS.
100*df_work.isna().mean().sort_values(ascending = False)

shipping_status       10.00060
customer_email         5.00000
customer_city          1.99960
tax_amount             0.99980
shipping_cost          0.49985
price_per_unit         0.20000
total_weight           0.09995
customer_country       0.00000
customer_id            0.00000
order_date             0.00000
order_id               0.00000
customer_name          0.00000
customer_address       0.00000
country_code           0.00000
quantity               0.00000
product_category       0.00000
product_name           0.00000
product_id             0.00000
discount_amount        0.00000
total_amount_gross     0.00000
final_total_amount     0.00000
payment_method         0.00000
dtype: float64

In [ ]:
#IMPUTAR COLUMNA CATEGÓRICA
df_work['shipping_status'].value_counts(dropna=False)

shipping_status
Delivered     721743
Shipped       539946
Processing    359373
NaN           200112
Cancelled     179826
Name: count, dtype: int64

In [ ]:
df_work['shipping_status'] = df_work['shipping_status'].fillna('LOST_ORDER') #IMPUTAMOS VALORES FALTANTES.
df_work['shipping_status'] = df_work['shipping_status'].str.strip()          #ELIMINAR ESPACIOS VACIOS.
df_work['shipping_status'] = df_work['shipping_status'].str.upper()          #MAYUSCULAS.
#df_work['shipping_status'] = df_work['shipping_status'].str.replace("??????@@@$$$djfvsijdvn",pd.na)
df_work['shipping_status'].value_counts(dropna=False)

shipping_status
DELIVERED     721743
SHIPPED       539946
PROCESSING    359373
LOST_ORDER    200112
CANCELLED     179826
Name: count, dtype: int64

In [ ]:
100*df_work.isna().mean().sort_values(ascending = False)

customer_email        5.00000
customer_city         1.99960
tax_amount            0.99980
shipping_cost         0.49985
price_per_unit        0.20000
total_weight          0.09995
customer_country      0.00000
customer_name         0.00000
customer_id           0.00000
order_date            0.00000
order_id              0.00000
product_id            0.00000
customer_address      0.00000
country_code          0.00000
quantity              0.00000
product_category      0.00000
product_name          0.00000
total_amount_gross    0.00000
discount_amount       0.00000
final_total_amount    0.00000
payment_method        0.00000
shipping_status       0.00000
dtype: float64

In [ ]:
#IMPUTAR COLUMNA NUMÉRICA
sum    = df_work['shipping_cost'].sum()
mean   = df_work['shipping_cost'].mean()
median = df_work['shipping_cost'].median()
std    = df_work['shipping_cost'].std()
max    = df_work['shipping_cost'].max()
min    = df_work['shipping_cost'].min()

In [ ]:
df_work['shipping_cost'] = df_work['shipping_cost'].fillna(median)

In [ ]:
100*df_work.isna().mean().sort_values(ascending = False)

customer_email        5.00000
customer_city         1.99960
tax_amount            0.99980
price_per_unit        0.20000
total_weight          0.09995
order_id              0.00000
customer_country      0.00000
customer_name         0.00000
customer_id           0.00000
order_date            0.00000
product_id            0.00000
product_name          0.00000
customer_address      0.00000
country_code          0.00000
quantity              0.00000
product_category      0.00000
total_amount_gross    0.00000
shipping_cost         0.00000
discount_amount       0.00000
final_total_amount    0.00000
payment_method        0.00000
shipping_status       0.00000
dtype: float64

In [ ]:
#DUPLICADOS
df_work.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
df_work[df_work.duplicated(keep = False)].sort_values(by = 'customer_id', ascending = False).head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
2000982,95174639-d54c-4d9b-9390-a695a25e5130,2024-03-08,400996,Benjamín García,benjamín.garcía_400996@example.com,Colombia,COL,Cartagena,1344 Calle Sur,P008,Office Chair,Furniture,3,200.0,45.0,72.50,600.0,30.0,108.30,750.80,Debit Card,DELIVERED
67474,95174639-d54c-4d9b-9390-a695a25e5130,2024-03-08,400996,Benjamín García,benjamín.garcía_400996@example.com,Colombia,COL,Cartagena,1344 Calle Sur,P008,Office Chair,Furniture,3,200.0,45.0,72.50,600.0,30.0,108.30,750.80,Debit Card,DELIVERED
2000462,9e0ec4b1-787e-4e3c-8230-82e50e23a50f,2024-09-08,400960,Valentina Torres,valentina.torres_400960@example.com,Argentina,ARG,Mar del Plata,6077 Calle Este,P019,Sneakers,Fashion,1,85.0,0.7,6.05,85.0,0.0,16.15,107.20,Debit Card,SHIPPED
216121,9e0ec4b1-787e-4e3c-8230-82e50e23a50f,2024-09-08,400960,Valentina Torres,valentina.torres_400960@example.com,Argentina,ARG,Mar del Plata,6077 Calle Este,P019,Sneakers,Fashion,1,85.0,0.7,6.05,85.0,0.0,16.15,107.20,Debit Card,SHIPPED
2000096,5fe7105f-5dc4-4740-bcc4-0c66724f5413,2024-06-12,400907,Isabel Muñoz,isabel.muñoz_400907@example.com,México,MEX,Monterrey,3412 Calle Oeste,P014,Microwave Oven,Home,1,150.0,10.0,20.00,150.0,15.0,25.65,180.65,Debit Card,PROCESSING

In [ ]:
df_work = df_work.drop_duplicates(keep = 'first')

In [ ]:
df_work['order_date'] = pd.to_datetime(df_work['order_date'], format = '%Y-%m-%d')

/tmp/ipykernel_589/1436791924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['order_date'] = pd.to_datetime(df_work['order_date'], format = '%Y-%m-%d')

In [ ]:
df_work.dtypes

order_id                      object
order_date            datetime64[ns]
customer_id                    int64
customer_name                 object
customer_email                object
customer_country              object
country_code                  object
customer_city                 object
customer_address              object
product_id                    object
product_name                  object
product_category              object
quantity                       int64
price_per_unit               float64
total_weight                 float64
shipping_cost                float64
total_amount_gross           float64
discount_amount              float64
tax_amount                   float64
final_total_amount           float64
payment_method                object
shipping_status               object
dtype: object

In [ ]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,DELIVERED
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,SHIPPED
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,SHIPPED
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.6,5.90,35.0,0.0,6.650,47.550,PayPal,DELIVERED
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.0,0.2,5.30,800.0,40.0,144.400,909.700,Bank Transfer,DELIVERED

In [ ]:
#GUARDAR DATA LIMPIA.
df_clean = df_work.copy(deep = True)

In [ ]:
#BONUS EXTRA: GENERAR LISTAS DETECTANDO AUTOMÁTICA EL TIPO DE DATO CON EL MÉTODO select_dtypes()
cols_numericas   = df_work.select_dtypes(include=['number']).columns.tolist()
cols_categoricas = df_work.select_dtypes(include=['object']).columns.tolist()

In [ ]:
cols_categoricas

['order_id',
 'customer_name',
 'customer_email',
 'customer_country',
 'country_code',
 'customer_city',
 'customer_address',
 'product_id',
 'product_name',
 'product_category',
 'payment_method',
 'shipping_status']

In [ ]:
df_work[cols_categoricas].head()

,order_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,Bank Transfer,Delivered

In [ ]:
#VEAMOS LAS LISTAS CON LOS NOMBRES DE COLUMNAS DE CADA TIPO: ESTO ES ÚTIL PARA DARLE EL TRATAMIENTO CORRESPONDIENTE A CADA TIPO DE DATO.
print(f"- Columnas numéricas   : {cols_numericas}")
print(f"- Columnas categóricas : {cols_categoricas}")

- Columnas numéricas   : ['customer_id', 'quantity', 'price_per_unit', 'total_weight', 'shipping_cost', 'total_amount_gross', 'discount_amount', 'tax_amount', 'final_total_amount']
- Columnas categóricas : ['order_id', 'customer_name', 'customer_email', 'customer_country', 'country_code', 'customer_city', 'customer_address', 'product_id', 'product_name', 'product_category', 'payment_method', 'shipping_status']

## 🚩 __CLASIFICACIÓN DE VALORES NULOS <code>NaN</code>__ 👽
---

* __MCAR (MISSING COMPLETLY AT RANDOM):__ Cada registro que es nulo lo hace sin nungún patron específico. Es decir, cualquiera de los registros tiene la misma chance de estar vacío. RECOMENDACIÓN: ELIMINAR O IMPUTAR (MEDIA O LA MEDIANA)

* __MAR (MISSING AT RANDOM):__ Hay valores nulos, pero estos se relacionan con otra columna específica. EJ: Hay valores nulos, pero estos se asocian a una o varias columnas.

* __MNAR (MISSING AT NO RANDOM):__ El valor no está o aparece nulo, pero no es al azar. Por ejemplo: Persona de áreas ricas de la ciudad, no dan su nombre por privacidad, por lo que la coluna user_name, suele tener nulos.

In [ ]:
df_work['shipping_status'].isna().groupby(df_work['customer_country']).mean().sort_values(ascending = False)

customer_country
Colombia     0.100476
México       0.100435
Chile        0.099911
Brasil       0.099810
Argentina    0.099712
Uruguay      0.099691
Ecuador      0.099665
Perú         0.099519
Name: shipping_status, dtype: float64

In [ ]:
df_work['order_date'] = df_work['order_date'].astype('datetime64[ns]')

In [ ]:
df_work = df_raw.dropna(subset = ['shipping_status'])

In [ ]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.0,0.3,5.45,250.0,0.0,47.500,302.950,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.0,0.6,5.90,35.0,3.5,5.985,43.385,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.0,15.0,27.50,200.0,10.0,36.100,253.600,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.6,5.90,35.0,0.0,6.650,47.550,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.0,0.2,5.30,800.0,40.0,144.400,909.700,Bank Transfer,Delivered

## __♻️ Funciones en Python 🚀__

Las funciones son una metedología de generación de un esquema general de un proceso repetitivo en python. Se caracateriza al igual que cualquier función por tener entrada - proceso - salida.